'use strict';

const assert = require('assert');
const port = Number(process.argv[2] || 9222);
const baseUrl = String(process.argv[3] || 'http://127.0.0.1:8010').replace(/\/$/, '');
const pages = [
  ['passwortgenerator', 'password-generator'], ['passwortstaerke-pruefen', 'strength'],
  ['zufallsstring-generator', 'random'], ['text-verschluesseln-entschluesseln', 'text-crypto'],
  ['datei-verschluesseln-entschluesseln', 'file-crypto'], ['datei-pruefsumme', 'checksum']
];
function delay(ms) { return new Promise((resolve) => setTimeout(resolve, ms)); }

(async function () {
  const targets = await (await fetch(`http://127.0.0.1:${port}/json`)).json();
  const target = targets.find((item) => item.type === 'page');
  if (!target) throw new Error('Keine Brave/Chromium-Testseite gefunden.');
  const socket = new WebSocket(target.webSocketDebuggerUrl); const pending = new Map(); const listeners = new Map(); let nextId = 1;
  socket.addEventListener('message', (event) => { const message = JSON.parse(event.data); if (message.id && pending.has(message.id)) { const callback = pending.get(message.id); pending.delete(message.id); if (message.error) callback.reject(new Error(JSON.stringify(message.error))); else callback.resolve(message.result); return; } (listeners.get(message.method) || []).forEach((listener) => listener(message.params)); });
  await new Promise((resolve, reject) => { socket.addEventListener('open', resolve); socket.addEventListener('error', reject); });
  function command(method, params = {}) { return new Promise((resolve, reject) => { const id = nextId++; pending.set(id, { resolve, reject }); socket.send(JSON.stringify({ id, method, params })); }); }
  function once(method, timeout = 20000) { return new Promise((resolve, reject) => { const handler = (params) => { clean(); resolve(params); }; const timer = setTimeout(() => { clean(); reject(new Error(`Browser-Ereignis ${method} blieb aus.`)); }, timeout); function clean() { clearTimeout(timer); listeners.set(method, (listeners.get(method) || []).filter((item) => item !== handler)); } listeners.set(method, [...(listeners.get(method) || []), handler]); }); }
  async function evaluate(expression, awaitPromise = false) { const result = await command('Runtime.evaluate', { expression, awaitPromise, returnByValue: true }); if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails)); return result.result.value; }
  async function waitFor(expression, timeout = 30000) { const started = Date.now(); while (Date.now() - started < timeout) { if (await evaluate(expression)) return; await delay(80); } throw new Error(`Wartezeit überschritten: ${expression}`); }
  async function navigate(slug, tool) { await command('Network.setBlockedURLs', { urls: [] }); const loaded = once('Page.loadEventFired'); await command('Page.navigate', { url: `${baseUrl}/tools/sicherheit/${slug}/` }); await loaded; await waitFor(`document.querySelector('[data-security-tool="${tool}"]')?.dataset.initialized === 'true'`); }
  async function setValue(selector, value) { await evaluate(`(() => { const node=document.querySelector(${JSON.stringify(selector)}); node.value=${JSON.stringify(value)}; node.dispatchEvent(new Event('input',{bubbles:true})); node.dispatchEvent(new Event('change',{bubbles:true})); return true; })()`); }
  async function click(action) { await evaluate(`document.querySelector('[data-action="${action}"]').click(); true`); }
  async function setFile(selector, name, type, values) { await evaluate(`(() => { const file=new File([Uint8Array.from(${JSON.stringify(values)})],${JSON.stringify(name)},{type:${JSON.stringify(type)}}); const transfer=new DataTransfer(); transfer.items.add(file); const input=document.querySelector(${JSON.stringify(selector)}); input.files=transfer.files; input.dispatchEvent(new Event('change',{bubbles:true})); return input.files[0].size; })()`); }

  await Promise.all([command('Page.enable'), command('Runtime.enable'), command('Network.enable')]);
  const exceptions = []; listeners.set('Runtime.exceptionThrown', [(params) => exceptions.push(params.exceptionDetails.text || 'Ausnahme')]);

  for (const [slug, tool] of pages) {
    await navigate(slug, tool);
    const shape = await evaluate(`(() => { const root=document.querySelector('[data-security-tool="${tool}"]'); const rect=root.getBoundingClientRect(); return { initialized:root.dataset.initialized, visible:rect.width>0&&rect.height>0, form:!!root.querySelector('form'), status:!!root.querySelector('[data-status]') }; })()`);
    assert.deepStrictEqual(shape, { initialized: 'true', visible: true, form: true, status: true }, `${slug}: reale UI initialisiert`);
    assert.ok((await evaluate('document.body.textContent')).includes('lokal in deinem Browser'), `${slug}: lokaler Hinweis sichtbar`);
  }

  await navigate('passwortgenerator', 'password-generator'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); await setValue('[data-length]', '48'); await click('run'); const password = await evaluate("document.querySelector('[data-output]').value"); assert.strictEqual(password.length, 48, 'Passwortlänge im UI'); assert.ok(/[a-z]/.test(password) && /[A-Z]/.test(password) && /\d/.test(password) && /[^A-Za-z0-9]/.test(password), 'alle Gruppen im UI');

  await navigate('passwortstaerke-pruefen', 'strength'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); await setValue('[data-password]', 'abcabcabcabc'); const weakScore = Number(await evaluate("document.querySelector('[data-strength-meter]').value")); await setValue('[data-password]', 'wT7!mQ2#vL9@xR4$kP8&nC6*'); const strongScore = Number(await evaluate("document.querySelector('[data-strength-meter]').value")); assert.ok(weakScore <= 2 && strongScore >= 4, 'schwache und starke Beispiele unterscheidbar'); assert.ok((await evaluate("document.querySelector('[data-feedback]').textContent")).length > 10, 'textuelles Feedback');

  await navigate('zufallsstring-generator', 'random'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); await setValue('[data-mode]', 'hex'); await setValue('[data-length]', '64'); await setValue('[data-count]', '3'); await click('run'); const strings = await evaluate("document.querySelector('[data-output]').value.split('\\n')"); assert.strictEqual(strings.length, 3, 'mehrere Zufallsstrings'); strings.forEach((value) => assert.ok(/^[0-9a-f]{64}$/.test(value), 'Hex-Modus'));

  await navigate('text-verschluesseln-entschluesseln', 'text-crypto'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); const originalText = 'Grüße aus Wien 🐼\nOffline.'; await setValue('[data-plain]', originalText); await setValue('[data-encrypt-passphrase]', 'browser test passwort'); const desktopStarted = Date.now(); await click('encrypt'); await waitFor("document.querySelector('[data-encrypted-output]').value.startsWith('SPENC-TEXT-1.')"); const desktopCryptoMs = Date.now() - desktopStarted; const packageValue = await evaluate("document.querySelector('[data-encrypted-output]').value"); await click('transfer'); await setValue('[data-decrypt-passphrase]', 'browser test passwort'); await click('decrypt'); await waitFor("document.querySelector('[data-decrypted-output]').value.length > 0"); assert.strictEqual(await evaluate("document.querySelector('[data-decrypted-output]').value"), originalText, 'Text-Roundtrip offline'); await setValue('[data-decrypt-passphrase]', 'falsch'); await click('decrypt'); await waitFor("document.querySelector('.security-tool-app').dataset.errorCode === 'authentication_failed'"); assert.strictEqual(await evaluate("document.querySelector('[data-decrypted-output]').value"), '', 'keine Ausgabe bei Authentifizierungsfehler'); assert.ok(packageValue.length > originalText.length, 'versionierter Container sichtbar'); assert.ok(desktopCryptoMs < 15000, 'PBKDF2/AES-GCM am Desktop-Viewport bedienbar');

  await navigate('datei-verschluesseln-entschluesseln', 'file-crypto'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); const originalBytes = [0, 1, 2, 3, 10, 13, 128, 255, 42]; await setFile('[data-encrypt-file]', 'prüfung.bin', 'application/octet-stream', originalBytes); await setValue('[data-encrypt-passphrase]', 'datei browser passwort'); await setValue('[data-confirm-passphrase]', 'datei browser passwort'); await click('encrypt'); await waitFor("document.querySelector('.security-tool-app').dataset.encryptedReady === 'true'", 40000); const encryptedSize = await evaluate("document.querySelector('.security-tool-app')._getEncryptedResultForTest().data.length"); assert.ok(encryptedSize > originalBytes.length, 'Dateicontainer erstellt'); await evaluate(`(() => { const app=document.querySelector('.security-tool-app'); const result=app._getEncryptedResultForTest(); const file=new File([result.data],result.filename,{type:'application/octet-stream'}); const transfer=new DataTransfer(); transfer.items.add(file); const input=document.querySelector('[data-decrypt-file]'); input.files=transfer.files; input.dispatchEvent(new Event('change',{bubbles:true})); return true; })()`); await setValue('[data-decrypt-passphrase]', 'datei browser passwort'); await click('decrypt'); await waitFor("document.querySelector('.security-tool-app').dataset.decryptedReady === 'true'", 40000); assert.strictEqual(await evaluate("document.querySelector('.security-tool-app').dataset.decryptedFilename"), 'prüfung.bin', 'Dateiname wiederhergestellt'); assert.deepStrictEqual(await evaluate("Array.from(document.querySelector('.security-tool-app')._getDecryptedResultForTest().data)"), originalBytes, 'Datei im realen UI bytegenau wiederhergestellt'); assert.ok((await evaluate("document.querySelector('[data-status]').textContent")).includes('entschlüsselt'), 'Datei erfolgreich entschlüsselt');

  await navigate('datei-pruefsumme', 'checksum'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); await setFile('[data-hash-file]', 'abc.txt', 'text/plain', [97, 98, 99]); await click('run'); await waitFor("document.querySelector('[data-hex]').value.length === 64"); const digest = await evaluate("document.querySelector('[data-hex]').value"); assert.strictEqual(digest, 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad', 'SHA-256 im Datei-UI'); await setValue('[data-expected]', 'BA78 16BF 8F01 CFEA 4141 40DE 5DAE 2223 B003 61A3 9617 7A9C B410 FF61 F200 15AD'); await click('compare'); assert.ok((await evaluate("document.querySelector('[data-comparison]').textContent")).includes('Übereinstimmung'), 'passender Vergleich'); await setValue('[data-expected]', '00'.repeat(32)); await click('compare'); assert.ok((await evaluate("document.querySelector('[data-comparison]').textContent")).includes('Keine Übereinstimmung'), 'Mismatch sichtbar');

  for (const width of [320, 375, 390, 430, 768, 1024, 1280, 1440, 1920]) {
    await command('Emulation.setDeviceMetricsOverride', { width, height: 1000, deviceScaleFactor: 1, mobile: width < 768 });
    const selected = width % 3 === 0 ? ['datei-verschluesseln-entschluesseln', 'file-crypto'] : width % 2 === 0 ? ['text-verschluesseln-entschluesseln', 'text-crypto'] : ['datei-pruefsumme', 'checksum']; await navigate(selected[0], selected[1]);
    const layout = await evaluate(`(() => { const root=document.querySelector('[data-security-tool]'); const actions=[...document.querySelectorAll('.tool-actions')]; const fields=[...document.querySelectorAll('textarea,input,select')]; const viewport=document.documentElement.clientWidth; return { bodyOverflow:document.documentElement.scrollWidth>viewport, scrollWidth:document.documentElement.scrollWidth, viewport, offenders:[...document.querySelectorAll('body *')].filter((node)=>node.getBoundingClientRect().right>viewport+1).slice(0,5).map((node)=>node.tagName+'.'+node.className), rootWidth:root.getBoundingClientRect().width, actionOverflow:actions.some((node)=>node.getBoundingClientRect().right>viewport+1), fieldOverflow:fields.some((node)=>node.getBoundingClientRect().right>viewport+1) }; })()`);
    assert.strictEqual(layout.bodyOverflow, false, `${width}px: kein horizontaler Body-Overflow (${JSON.stringify(layout)})`); assert.ok(layout.rootWidth > 0, `${width}px: Tool sichtbar`); assert.strictEqual(layout.actionOverflow, false, `${width}px: Aktionen erreichbar`); assert.strictEqual(layout.fieldOverflow, false, `${width}px: Felder erreichbar`);
  }
  await command('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true }); await navigate('text-verschluesseln-entschluesseln', 'text-crypto'); await command('Network.setBlockedURLs', { urls: ['http://*', 'https://*'] }); await setValue('[data-plain]', 'Mobiler PBKDF2-Lauf 🐼'); await setValue('[data-encrypt-passphrase]', 'mobiles browser passwort'); const mobileStarted = Date.now(); await click('encrypt'); await waitFor("document.querySelector('[data-encrypted-output]').value.startsWith('SPENC-TEXT-1.')"); const mobileCryptoMs = Date.now() - mobileStarted; assert.ok(mobileCryptoMs < 15000, 'PBKDF2/AES-GCM am mobilen Viewport bedienbar');
  await command('Emulation.clearDeviceMetricsOverride'); assert.deepStrictEqual(exceptions, [], 'keine unbehandelten Browser-Ausnahmen');
  console.log(`SECURITY-PAGES-BROWSER ERFOLGREICH: 6 reale UIs, Offline-Krypto/Datei/SHA-2, 9 Viewports; PBKDF2/AES Desktop ${desktopCryptoMs} ms, mobil emuliert ${mobileCryptoMs} ms`); socket.close();
}()).catch((error) => { console.error(error); process.exit(1); });
